CREATE DATABASE IF NOT EXISTS {{DB_NAME}};
USE {{DB_NAME}};

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token_value VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Password: password123 (hashed via SHA-256)
INSERT IGNORE INTO users (username, password_hash) 
VALUES ('root', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f');